In [1]:
%load_ext kedro.ipython

[11/29/22 23:57:41] INFO     Updated path to Kedro project:                                          ]8;id=392147;file:///Users/simonmyway/opt/anaconda3/envs/abssa-cal/lib/python3.10/site-packages/kedro/ipython/__init__.py\__init__.py]8;;\:]8;id=300538;file:///Users/simonmyway/opt/anaconda3/envs/abssa-cal/lib/python3.10/site-packages/kedro/ipython/__init__.py#54\54]8;;\
                             /Users/simonmyway/Documents/code/myway/abssa-calendar/abssa-calendar

[11/29/22 23:57:42] INFO     Kedro project ABSSA calendar                                            ]8;id=119923;file:///Users/simonmyway/opt/anaconda3/envs/abssa-cal/lib/python3.10/site-packages/kedro/ipython/__init__.py\__init__.py]8;;\:]8;id=845368;file:///Users/simonmyway/opt/anaconda3/envs/abssa-cal/lib/python3.10/site-packages/kedro/ipython/__init__.py#77\77]8;;\

                    INFO     Defined global variable 'context', 'session', 'catalog' and 'pipelines' ]8;id=787662;file:///Users/simonmyway/opt/anaconda3/envs/abssa-cal/lib/python3.10/site-packages/kedro/ipython/__init__.py\__init__.py]8;;\:]8;id=584396;file:///Users/simonmyway/opt/anaconda3/envs/abssa-cal/lib/python3.10/site-packages/kedro/ipython/__init__.py#78\78]8;;\

                    INFO     Registered line magic 'run_viz'                                         ]8;id=609032;file:///Users/simonmyway/opt/anaconda3/envs/abssa-cal/lib/python3.10/site-packages/kedro/ipython/__init__.py\__init__.py]8;;\:]8;id=384899;file:///Users/simonmyway/opt/anaconda3/envs/abssa-cal/lib/python3.10/site-packages/kedro/ipython/__init__.py#84\84]8;;\

In [5]:
%reload_kedro

[11/29/22 23:59:01] INFO     No path argument was provided. Using:                                   ]8;id=509490;file:///Users/simonmyway/opt/anaconda3/envs/abssa-cal/lib/python3.10/site-packages/kedro/ipython/__init__.py\__init__.py]8;;\:]8;id=995672;file:///Users/simonmyway/opt/anaconda3/envs/abssa-cal/lib/python3.10/site-packages/kedro/ipython/__init__.py#56\56]8;;\
                             /Users/simonmyway/Documents/code/myway/abssa-calendar/abssa-calendar

[11/29/22 23:59:01] INFO     Kedro project ABSSA calendar                                            ]8;id=669026;file:///Users/simonmyway/opt/anaconda3/envs/abssa-cal/lib/python3.10/site-packages/kedro/ipython/__init__.py\__init__.py]8;;\:]8;id=718225;file:///Users/simonmyway/opt/anaconda3/envs/abssa-cal/lib/python3.10/site-packages/kedro/ipython/__init__.py#77\77]8;;\

                    INFO     Defined global variable 'context', 'session', 'catalog' and 'pipelines' ]8;id=801727;file:///Users/simonmyway/opt/anaconda3/envs/abssa-cal/lib/python3.10/site-packages/kedro/ipython/__init__.py\__init__.py]8;;\:]8;id=120428;file:///Users/simonmyway/opt/anaconda3/envs/abssa-cal/lib/python3.10/site-packages/kedro/ipython/__init__.py#78\78]8;;\

                    INFO     Registered line magic 'run_viz'                                         ]8;id=694031;file:///Users/simonmyway/opt/anaconda3/envs/abssa-cal/lib/python3.10/site-packages/kedro/ipython/__init__.py\__init__.py]8;;\:]8;id=990605;file:///Users/simonmyway/opt/anaconda3/envs/abssa-cal/lib/python3.10/site-packages/kedro/ipython/__init__.py#84\84]8;;\

In [2]:
fixtures_df = catalog.load("fixtures_primary")
fixtures_df.head()

[11/29/22 23:58:11] INFO     Loading data from 'fixtures_primary' (CSVDataSet)...               ]8;id=175258;file:///Users/simonmyway/opt/anaconda3/envs/abssa-cal/lib/python3.10/site-packages/kedro/io/data_catalog.py\data_catalog.py]8;;\:]8;id=314211;file:///Users/simonmyway/opt/anaconda3/envs/abssa-cal/lib/python3.10/site-packages/kedro/io/data_catalog.py#343\343]8;;\

,home_club_id,away_club_id,time,division,date,day,played,result,datetime_start,datetime_end
0,999,455,00:00,4B,2022-09-03,1,False,NaN,2022-09-03 00:00:00+02:00,2022-09-03 01:25:00+02:00
1,999,445,00:00,4B,2022-09-03,1,False,NaN,2022-09-03 00:00:00+02:00,2022-09-03 01:25:00+02:00
2,522,412,NaN,4B,2022-09-03,1,True,1-1,NaN,NaN
3,345,497,NaN,4B,2022-09-03,1,True,4-2,NaN,NaN
4,306,359,NaN,4B,2022-09-03,1,True,3-0,NaN,NaN

In [6]:
clubs_teams_df = catalog.load("clubs_teams_primary")
clubs_teams_df.head()

[11/29/22 23:59:03] INFO     Loading data from 'clubs_teams_primary' (CSVDataSet)...            ]8;id=33332;file:///Users/simonmyway/opt/anaconda3/envs/abssa-cal/lib/python3.10/site-packages/kedro/io/data_catalog.py\data_catalog.py]8;;\:]8;id=301459;file:///Users/simonmyway/opt/anaconda3/envs/abssa-cal/lib/python3.10/site-packages/kedro/io/data_catalog.py#343\343]8;;\

,club_id,team_id,game_time,division,artificial_grass,field_id,color,club_name,secretary,phone_number,email,club_url,club_team_id,club_team_name
0,427,1,12:30,6E,True,A08,Jaune et bleu,AEMA VETERANS,VAN INGELGOM J.,0475.36.44.88,vaningelgom_w_j@hotmail.com,https://www.abssa.org/team/427/AEMA-VETERANS,427_1,AEMA VETERANS
1,395,1,14:00,6C,True,A08,Jaune,ALIZE VETERANS FC,HAENTJENS J-L.,0473.88.82.20,jean-luc.haentjens@police.belgium.eu,https://www.abssa.org/team/395/ALIZE-VETERANS-FC,395_1,ALIZE VETERANS FC
2,249,1,15:30,1,True,A11,Noir,AMB. AUDERGHEM,LECLEF R.,0473.13.76.27,renaudleclef@hotmail.fr,https://www.abssa.org/team/249/AMB-AUDERGHEM,249_1,AMB. AUDERGHEM
3,249,2,14:00,6A,True,A11,Blanc rayé de Gris,AMB. AUDERGHEM,LECLEF R.,0473.13.76.27,renaudleclef@hotmail.fr,https://www.abssa.org/team/249/AMB-AUDERGHEM,249_2,AMB. AUDERGHEM (Eq. 2)
4,280,1,14:00,6C,True,A09,Mauve,ANDERLECHT US,SADIN D.,0477.76.34.69,usanderlecht@sadinfoot.net,https://www.abssa.org/team/280/ANDERLECHT-US,280_1,ANDERLECHT US

In [15]:
c = ["home_club_id", "division", "time"]
s = fixtures_df["time"].notna()
fixtures_time = fixtures_df.loc[s, c].drop_duplicates()
fixtures_time = fixtures_time.rename(columns = {"home_club_id":"club_id", "time":"game_time"})

In [16]:
c = ["club_id", "division", "game_time"]
clubs_teams_time = clubs_teams_df[c]

In [22]:
times = clubs_teams_time.merge(fixtures_time, on=["club_id", "division"], suffixes=("_ct", "_f"))

In [25]:
diff = ~(times["game_time_ct"] == times["game_time_f"])

In [26]:
diff.sum()

3

In [28]:
times.loc[diff]

,club_id,division,game_time_ct,game_time_f
70,303,6D,12:30,11:00
85,338,5B,15:30,14:00
227,574,4D,13:30,13:00

In [41]:
#k = fixtures_df["time"] == "11:00"
k = fixtures_df["division"] == "5B"
k &= fixtures_df["home_club_id"] == 338
fixtures_df.loc[k]

,home_club_id,away_club_id,time,division,date,day,played,result,datetime_start,datetime_end
87,338,999,14:00,5B,2022-09-03,1,False,NaN,2022-09-03 14:00:00+02:00,2022-09-03 15:25:00+02:00
397,338,417,NaN,5B,2022-09-17,3,True,2-1,NaN,NaN
642,338,619,NaN,5B,2022-10-01,5,True,1-3,NaN,NaN
853,338,652,NaN,5B,2022-10-15,7,True,3-2,NaN,NaN
1131,338,514,NaN,5B,2022-11-05,9,True,0-2,NaN,NaN
1480,338,498,NaN,5B,2022-11-26,12,True,1-2,NaN,NaN
1720,338,655,15:30,5B,2022-12-03,13,False,NaN,2022-12-03 15:30:00+01:00,2022-12-03 16:55:00+01:00
1977,338,661,15:30,5B,2022-12-17,15,False,NaN,2022-12-17 15:30:00+01:00,2022-12-17 16:55:00+01:00
2091,338,659,15:30,5B,2023-01-07,16,False,NaN,2023-01-07 15:30:00+01:00,2023-01-07 16:55:00+01:00
2330,338,593,15:30,5B,2023-01-21,18,False,NaN,2023-01-21 15:30:00+01:00,2023-01-21 16:55:00+01:00
2595,338,572,15:30,5B,2023-02-04,20,False,NaN,2023-02-04 15:30:00+01:00,2023-02-04 16:55:00+01:00
2980,338,635,15:30,5B,2023-03-04,23,False,NaN,2023-03-04 15:30:00+01:00,2023-03-04 16:55:00+01:00
3177,338,330,15:30,5B,2023-03-11,24,False,NaN,2023-03-11 15:30:00+01:00,2023-03-11 16:55:00+01:00

In [40]:
scope = ~fixtures_df["played"]

r = fixtures_df.loc[scope].groupby(["home_club_id", "division"])["time"].apply(lambda x: len(x.unique())).sort_values()
r.loc[r>1]

home_club_id  division
338           5B          2
Name: time, dtype: int64

In [49]:
scope = ~fixtures_df["played"]
game_time = fixtures_df.loc[scope].groupby(["home_club_id", "division"], as_index=False)["time"].apply(lambda x: x.mode())
game_time = game_time.rename(columns={0:"time_most_frequent"})

,home_club_id,division,time_most_frequent
0,1,1,14:00
1,1,2B,15:30
2,1,3C,12:30
3,1,4A,12:30
4,1,6B,15:30
...,...,...,...
260,999,4D,00:00
261,999,5A,00:00
262,999,5B,00:00
263,999,5C,00:00
264,999,6E,00:00

In [51]:
fixtures_df = fixtures_df.merge(game_time, on=("home_club_id","division"))

In [55]:
fixtures_df["time"] = fixtures_df[['time', 'time_most_frequent']].bfill(axis=1).iloc[:, 0]

In [57]:
fixtures_df.loc[fixtures_df["played"]]

,home_club_id,away_club_id,time,division,date,day,played,result,datetime_start,datetime_end,time_most_frequent
26,522,412,12:30,4B,2022-09-03,1,True,1-1,NaN,NaN,12:30
28,522,606,12:30,4B,2022-09-24,4,True,1-3,NaN,NaN,12:30
30,522,628,12:30,4B,2022-10-22,8,True,3-1,NaN,NaN,12:30
31,522,39,12:30,4B,2022-11-19,11,True,5-2,NaN,NaN,12:30
39,345,497,14:00,4B,2022-09-03,1,True,4-2,NaN,NaN,14:00
...,...,...,...,...,...,...,...,...,...,...,...
3445,635,659,15:30,5B,2022-09-17,3,True,2-2,NaN,NaN,15:30
3446,635,593,15:30,5B,2022-10-01,5,True,1-1,NaN,NaN,15:30
3447,635,572,15:30,5B,2022-10-15,7,True,4-1,NaN,NaN,15:30
3449,635,338,15:30,5B,2022-11-12,10,True,4-3,NaN,NaN,15:30
3450,635,330,15:30,5B,2022-11-26,12,True,2-0,NaN,NaN,15:30